version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: matthis-f/node-js-sample
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Testing docker image
          command: docker run --rm -d --name=test -p 8080:8080 $IMAGE_NAME:latest && docker ps --last=1 && docker stop test
