version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: matthis-f/node-js-sample
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - test:
          name: Testing docker image
          command: docker run matthis-f/node-js-samble:latest
	
